parameters:
#    cat_core.example.class: Cat\CoreBundle\Example

# services:
#    cat_core.example:
#        class: %cat_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    user_service:
        class: Cat\CoreBundle\Service\UserService
        arguments: [ "@doctrine.orm.entity_manager" ]
